version: '3.1'

services:
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - mongodbData:/data/db
      - ./dataset:/dataset/
    ports:
      - 27017:27017
volumes:
  mongodbData:
    driver: local