version: '3.1'

services:
  taskapi:
    container_name: taskapi
    image: taskapi:1.0
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8003:8003
    depends_on:
      - mongo
    links:
      - mongo:mongo
    environment:
      database.hostname: mongo
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    volumes:
      - mongodbData:/data/db
      - ./dataset:/dataset/
    ports:
      - 27017:27017
volumes:
  mongodbData:
    driver: local